BL.EN.U4CSE21189 ; Siddhant Ashwani ; CSE-C

In [20]:
import numpy as np
import pandas as pd
import math

In [2]:
data = pd.read_excel(r'C:\Users\navin\Downloads\embeddingsdata.xlsx')
df = pd.DataFrame(data)

df

,embed_0,embed_1,embed_2,embed_3,embed_4,embed_5,embed_6,embed_7,embed_8,embed_9,...,embed_759,embed_760,embed_761,embed_762,embed_763,embed_764,embed_765,embed_766,embed_767,Label
0,0.009625,-0.029216,0.027109,0.023631,-0.004972,0.031757,-0.045125,0.044483,0.019400,-0.017189,...,-0.001972,-0.008154,-0.056139,0.009890,0.042366,0.040134,0.009304,-0.016137,-0.009309,0
1,-0.007535,-0.039844,0.030167,0.031224,0.004742,0.028289,-0.068723,0.039153,0.019596,-0.027138,...,0.008613,-0.006578,-0.034220,0.027574,0.045456,0.027402,0.017837,-0.035009,-0.010062,0
2,0.022408,-0.030840,0.032328,0.046965,0.007798,0.025860,-0.065093,0.035118,0.035359,-0.029205,...,0.020413,-0.034288,-0.050649,0.028408,0.040412,0.030261,0.003535,-0.034122,-0.017289,0
3,0.019677,-0.034055,0.012662,0.070387,-0.011170,0.017842,-0.050945,0.044878,0.034781,-0.025772,...,0.002963,-0.018754,-0.053278,0.033005,0.031635,0.022544,-0.011774,-0.011125,-0.017540,0
4,0.017678,-0.030323,0.012829,0.065267,-0.025161,0.011964,-0.050590,0.042820,0.029161,-0.015004,...,0.010192,-0.010147,-0.035857,0.021784,0.034621,0.017342,-0.009884,-0.010316,-0.029238,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,0.019743,-0.071799,0.022546,0.049042,-0.005767,-0.016275,-0.037731,0.029718,0.009203,-0.030913,...,-0.001192,-0.026138,-0.056447,0.015818,0.045241,0.012620,-0.004837,-0.014540,-0.046791,2
896,0.000186,-0.027604,0.010623,0.038237,-0.026675,0.020215,-0.040816,0.032210,0.041016,-0.014836,...,0.015479,-0.003967,-0.037808,0.021234,0.031012,-0.010890,0.003081,-0.015145,-0.045444,0
897,0.018066,-0.032152,0.039794,0.047608,0.003898,0.024092,-0.056508,0.020527,0.031972,-0.026038,...,0.011308,-0.016882,-0.059904,0.009558,0.039976,0.029574,0.013737,-0.003724,-0.017324,2
898,-0.003492,-0.022739,0.021777,0.044054,-0.005621,0.013863,-0.079196,0.039150,0.004557,-0.015787,...,0.004005,-0.007196,-0.041652,0.020945,0.047604,0.019767,0.005806,-0.019280,-0.016415,5
899,0.013689,-0.037855,0.039763,0.035750,0.004115,0.005637,-0.050556,0.024668,0.025077,-0.029114,...,-0.000129,-0.003880,-0.048696,0.015711,0.039773,0.036328,0.010483,-0.021304,-0.032017,2

A1. For the data table provided below, calculate the entropy associated with each attribute / feature at the root node. Using this information, identify the first feature that you’d select for constructing the decision tree. Use Information Gain as the impurity measure to identify the root node.‘buys_computer’ is the class label.

In [11]:
data1 = pd.read_excel(r"C:\Amrita cse\5th Semester\Machine Learning\Lab\Lab 4\lab4_data.xlsx")

df = pd.DataFrame(data1)

df

       age  income student credit_rating buys_computer
0     <=30    high      no          fair            no
1     <=30    high      no     excellent            no
2   31..40    high      no          fair           yes
3      >40  medium      no          fair           yes
4      >40     low     yes          fair           yes
5      >40     low     yes     excellent            no
6   31..40     low     yes     excellent           yes
7     <=30  medium      no          fair            no
8     <=30     low     yes          fair           yes
9      >40  medium     yes          fair           yes
10    <=30  medium     yes     excellent           yes
11  31..40  medium      no     excellent           yes
12  31..40    high     yes          fair           yes
13     >40  medium      no     excellent            no

In [21]:
#CALCULATING ENTROPY OF EACH FEATURE
def calculate_entropy(data):
    # Count the occurrences of each class
    class_counts = data['buys_computer'].value_counts()
    # Calculate the entropy
    entropy = 0
    total_samples = len(data)
    for count in class_counts:
        probability = count / total_samples
        entropy -= probability * np.log2(probability)
    return entropy

def calculate_root_entropy(data, features):
    root_entropy = calculate_entropy(data)
    feature_entropies = {}
    for feature in features:
        unique_values = data[feature].unique()
        feature_entropy = 0
        for value in unique_values:
            subset = data[data[feature] == value]
            feature_entropy += (len(subset) / len(data)) * calculate_entropy(subset)
        feature_entropies[feature] = feature_entropy
    return root_entropy, feature_entropies
# Specify the list of features (attributes)
features = ['age', 'income', 'student','credit_rating','buys_computer']
# Calculate root entropy and entropies for each feature
root_entropy, feature_entropies = calculate_root_entropy(df, features)
# Print the results
print(f"Root Entropy: {root_entropy}")
for feature, entropy in feature_entropies.items():
    print(f"Entropy for {feature}: {entropy}")

Root Entropy: 0.9402859586706311
Entropy for age: 0.6935361388961918
Entropy for income: 0.9110633930116763
Entropy for student: 0.7884504573082896
Entropy for credit_rating: 0.8921589282623617
Entropy for buys_computer: 0.0

In [24]:
import numpy as np
import pandas as pd

# Function to calculate entropy
def calculate_entropy(data):
    class_counts = data['buys_computer'].value_counts()
    entropy = 0
    total_samples = len(data)
    for count in class_counts:
        probability = count / total_samples
        entropy -= probability * np.log2(probability)
    return entropy

# Function to calculate information gain
def calculate_information_gain(root_entropy, feature_entropy):
    information_gain = root_entropy - feature_entropy
    return information_gain

df = pd.DataFrame(data1)

# Calculate root entropy
root_entropy = calculate_entropy(df)

# Calculate feature entropies
features = ['age', 'income', 'student', 'credit_rating']
information_gains = {}

for feature in features:
    unique_values = df[feature].unique()
    feature_entropy = 0
    for value in unique_values:
        subset = df[df[feature] == value]
        feature_entropy += (len(subset) / len(df)) * calculate_entropy(subset)
    feature_entropies[feature] = feature_entropy
    information_gains[feature] = calculate_information_gain(root_entropy, feature_entropy)

# Calculate information gain for each feature
information_gains = {feature: calculate_information_gain(root_entropy, entropy) for feature, entropy in feature_entropies.items()}

# Print the information gains
for feature, gain in information_gains.items():
    print(f"Information Gain for {feature}: {gain:.4f}")

# Select the feature with the highest information gain as the root node
root_node = max(information_gains, key=information_gains.get)

print(f"The root node is: {root_node} with information gain {information_gains[root_node]:.4f}")

Information Gain for age: 0.2467
Information Gain for income: 0.0292
Information Gain for student: 0.1518
Information Gain for credit_rating: 0.0481
The root node is: age with information gain 0.2467